###----------- Configuração -----------###
@base_url = http://localhost:8000

###----------- Usuário ----------------------------------------###

POST {{base_url}}/usuarios/ HTTP/1.1
Content-Type: application/json

{
    "nome": "João das neves",
    "cpf": "12345673301",
    "data_nascimento": "1990-04-01",
    "idade": 33,
    "senha": "senhaSegura123",
    "email": "jeao@email.com",
    "usuario": "jeao_neves"
}

###


GET {{base_url}}/usuarios/ HTTP/1.1
Accept: application/json

###


PUT {{base_url}}/usuarios/1 HTTP/1.1
Content-Type: application/json

{
    "nome": "João Siqva Neves",
    "cpf": "12342278901",
    "data_nascimento": "1990-01-01",
    "idade": 37,
    "senha": "senhasegura123",
    "email": "joso@email.com",
    "usuario": "jsao_neves"
}

###
DELETE {{base_url}}/usuarios/18/delete HTTP/1.1
Accept: application/json




###----------- Avaliação --------------------------------------###
POST {{base_url}}/avaliacoes HTTP/1.1
Content-Type: application/json

{
   "nota_passageiro": 5,
   "nota_motorista": 5,
   "datahora_limite": "2026-03-23T10:10:10"
}

###
GET {{base_url}}/avaliacoes HTTP/1.1
Accept: application/json
###

PUT {{base_url}}/avaliacoes/1/update HTTP/1.1
Content-Type: application/json

{
  "nota_passageiro": 4
}

###
DELETE {{base_url}}/avaliacoes/6/delete HTTP/1.1
Accept: application/json





###----------- Classe -----------------------------------------###
POST {{base_url}}/classes HTTP/1.1
Content-Type: application/json

{
    "nome_classe": "Executivo",
    "fator_preco": 1.50
}


###
GET {{base_url}}/classes HTTP/1.1
Accept: application/json


###
PUT {{base_url}}/classes/2 HTTP/1.1
Content-Type: application/json

{
    "nome_classe" :"Executivo",
    "fator_preco": 0.75
}


###
DELETE {{base_url}}/classes/3/delete HTTP/1.1
Accept: application/json





###----------- Tipos de Combustível ---------------------------###

POST {{base_url}}/tipos_combustivel/ HTTP/1.1
Content-Type: application/json

{
    "descricao": "Gasolina Comum",
    "fator_carbono": 2.31
}

###
GET {{base_url}}/tipos_combustivel/ HTTP/1.1
Accept: application/json


###
PUT {{base_url}}/tipos_combustivel/1 HTTP/1.1
Content-Type: application/json

{
    "descricao": "Gasolina Aditivada",
    "fator_carbono": 2.45
}


###
DELETE {{base_url}}/tipos_combustivel/2/delete HTTP/1.1
Accept: application/json




###----------- Modelo Veículo ---------------------------------###

POST {{base_url}}/modelo_veiculo HTTP/1.1
Content-Type: application/json

{
    "nome_modelo": "Corolla",
    "cor": "Prata",
    "fabricante": "Toyota",
    "ano": 2025,
    "capacidade": 5,
    "propriedade": "Próprio",
    "id_combustivel": 1
}


###
GET {{base_url}}/modelo_veiculo HTTP/1.1
Accept: application/json


###
PUT {{base_url}}/modelo_veiculo/3 HTTP/1.1
Content-Type: application/json

{
    "nome_modelo": "Corolla", 
    "cor": "Branco", 
    "fabricante": "Toyota", 
    "ano": 2024, 
    "capacidade": 5, 
    "propriedade": "Alugado", 
    "id_combustivel": 1
}


###
DELETE {{base_url}}/modelo_veiculo/4/delete HTTP/1.1
Accept: application/json




###----------- Veículo ----------------------------------------###


POST {{base_url}}/veiculo/ HTTP/1.1
Content-Type: application/json

{
    "placa": "BRA2E19",
    "id_modelo": 2,
    "tem_seguro": 1,
    "id_classe": 4
}


###
GET {{base_url}}/veiculo HTTP/1.1
Accept: application/json

###
PUT {{base_url}}/veiculo/17 HTTP/1.1
Content-Type: application/json

{
    "placa": "BEA2E19",
    "id_modelo": 2,
    "tem_seguro": 1,
    "id_classe": 4
}


###
DELETE {{base_url}}/veiculo/12/delete HTTP/1.1
Accept: application/json




###----------- Motorista --------------------------------------###

POST {{base_url}}/motoristas HTTP/1.1
Content-Type: application/json

{
    "id_usuario": 1,
    "media_avaliacao": 5.0,
    "cnh": "12345678901"
}

###
GET {{base_url}}/motoristas HTTP/1.1
Accept: application/json

###
PUT {{base_url}}/motoristas/1/update HTTP/1.1
Content-Type: application/json

{
    "media_avaliacao": 4.9
}

###
DELETE {{base_url}}/motoristas/1/delete HTTP/1.1
Accept: application/json





###----------- Passageiro -------------------------------------###

POST {{base_url}}/passageiros HTTP/1.1
Content-Type: application/json

{
    "id_usuario": 1,
    "media_avaliacao": 4.5
}

###
GET {{base_url}}/passageiros HTTP/1.1
Accept: application/json

###
PUT {{base_url}}/passageiros/1 HTTP/1.1
Content-Type: application/json

{
   "id_usuario": 1,
    "media_avaliacao": 4.6
}


###
DELETE {{base_url}}/passageiros/4/delete HTTP/1.1
Accept: application/json




###----------- Serviço ----------------------------------------###

POST {{base_url}}/servicos HTTP/1.1
Content-Type: application/json

{
    "nome_servico": "Black",
    "id_classe_minima": 5
}

###
GET {{base_url}}/servicos HTTP/1.1
Accept: application/json
###

PUT {{base_url}}/servicos/6 HTTP/1.1
Content-Type: application/json


    {
    "nome_servico": "Ligth",
    "id_classe_minima": 5
}


###
DELETE {{base_url}}/servicos/6/delete HTTP/1.1
Accept: application/json



###----------- Corrida ----------------------------------------###

POST {{base_url}}/corridas HTTP/1.1
Content-Type: application/json

{
    "id_passageiro": 2,
    "id_motorista": 3,
    "id_servico": 1,
    "datahora_inicio": "2026-04-23T14:00:00",
    "local_partida": "Rua das Flores, 123",
    "local_destino": "Aeroporto",
    "valor_estimado": 45.00,
    "status": "Pendente"
}  

###
GET {{base_url}}/corridas HTTP/1.1
Accept: application/json

###
PUT {{base_url}}/corridas/1 HTTP/1.1
Content-Type: application/json

{
    "id_passageiro": 2,
    "id_motorista": 3,
    "id_servico": 1,
    "datahora_inicio": "2026-05-23T14:00:00",
    "local_partida": "Rua das Flores, 123",
    "local_destino": "Aeroporto",
    "valor_estimado": 45.00,
    "status": "Pendente"
}

###
DELETE {{base_url}}/corridas/3/delete HTTP/1.1
Accept: application/json




###----------- Pagamento --------------------------------------###

POST {{base_url}}/pagamentos HTTP/1.1
Content-Type: application/json

{
    "id_corrida": 1,
    "valor": 45.00,
    "id_metodo_pagamento": 1,
    "datahora_transacao": "2026-03-23T14:50:00"
}


###
GET {{base_url}}/pagamentos HTTP/1.1
Accept: application/json

###
PUT {{base_url}}/pagamentos/1 HTTP/1.1
Content-Type: application/json

{
    "id_corrida": 1,
    "valor": 45.00,
    "id_metodo_pagamento": 1,
    "datahora_transacao": "2026-03-23T14:50:00"
}

###
DELETE {{base_url}}/pagamentos/3/delete HTTP/1.1
Accept: application/json






###----------- Método Pagamento -------------------------------###

POST {{base_url}}/metodos_pagamento HTTP/1.1
Content-Type: application/json

{
    "descricao": "Cartão de Crédito",
    "nome_financeira": "Mastercard"
}

###
GET {{base_url}}/metodos_pagamento HTTP/1.1
Accept: application/json


###
PUT {{base_url}}/metodos_pagamento/1 HTTP/1.1
Content-Type: application/json

{
    "descricao": "Cartão de Débito",
    "nome_financeira": "Mastercard"
}

###
DELETE {{base_url}}/metodos_pagamento/4/delete HTTP/1.1
Accept: application/json




###----------- Vínculo Motorista Veículo ----------------------###
POST {{base_url}}/motorista_veiculo HTTP/1.1
Content-Type: application/json

{
    "id_motorista": 3,
    "id_veiculo": 15,
    "datahora_inicio": "2026-03-23T08:00:00"
}

###
GET {{base_url}}/motorista_veiculo HTTP/1.1

###
PUT {{base_url}}/motorista_veiculo/15/3 HTTP/1.1
Content-Type: application/json

{
   "id_veiculo": 3,
   "id_motorista": 3,
    "datahora_inicio": "2026-07-23T18:00:00"
}

###
DELETE {{base_url}}/motorista_veiculo/3/3/delete HTTP/1.1
Accept: application/json